### ISSUE TITLE
前端少了GateWay 管理的页面

### ISSUE THREAD

**Issue by han1396735592** [zhangdaiscott/jeecg-cloud#13]
![image](https://user-images.githubusercontent.com/29246573/85221669-4afb7700-b3e8-11ea-933e-2d60c9a8a448.png)

**Comment by han1396735592** [comment]
@zhangdaiscott 这个管理页面，可否提供下

**Comment by zhangdaiscott** [comment]
最新版的前端已经提供了
https://github.com/zhangdaiscott/jeecg-boot/tree/master/ant-design-vue-jeecg
