### ISSUE TITLE
网关未进行跨域问题处理

### ISSUE THREAD

**Issue by han1396735592** [zhangdaiscott/jeecg-cloud#14]
![image](https://user-images.githubusercontent.com/29246573/85221958-a169b500-b3ea-11ea-917a-3afc8925be7b.png)

**Comment by zhangdaiscott** [comment]
处理过了，你是怎么用的

**Comment by han1396735592** [comment]
我自己加的，准备项目改造为微服务版本的。先做测试，跟boot版本的兼容性还不错
