### ISSUE TITLE
jeecg骨架工程创建新模块问题

### ISSUE THREAD

**Issue by Nicky213Zhang** [zhangdaiscott/jeecg-cloud#15]
使用jeecg骨架工程创建一个新模块
![image](https://user-images.githubusercontent.com/25654842/85239524-aff5b200-b466-11ea-8c1c-2f4f8e12103f.png)
第三部执行并没有选择出现Choose archetype:
1: local -> org.jeecgframework.cloud:jeecg-cloud-demo (beast-archetype)
2: local -> org.jeecgframework.cloud:jeecg-gen (beast-archetype)
3: local -> tech.qijin.archetype:qijin-quickstart (${artifactId})。
选择在idea添加模块方式也提示失败。

**Comment by wzd0424** [comment]
同样遇到该问题

**Comment by huang-gz** [comment]
我也遇到同样的问题啊

**Comment by zhangdaiscott** [comment]
看最新文档
http://doc.cloud.jeecg.com/1805010
