### ISSUE TITLE
慎用此开源项目

### ISSUE THREAD

**Issue by XuSanHong** [zhangdaiscott/jeecg-cloud#17]
这个开源项目是一个半成品，我们领导不知道哪儿看见这个项目，对此深信不疑，我已经提出来种种问题，然后领导还是坚持用，我已经快改疯了。。。开源出来的产品，至少要有一个稳定版本吧，或者表明一下有风险慎用吧，写的很豪华，然后拉下来看，各种问题。

**Comment by zhangdaiscott** [comment]
![Uploading image.png…]()
