### ISSUE TITLE
system模块无法启动

### ISSUE THREAD

**Issue by wyx666518** [zhangdaiscott/jeecg-cloud#2]
gateway已经成功启动，但system无法启动。
'parent.relativePath' of POM org.jeecgframework.cloud:jeecg-cloud-system-biz:[unknown-version] (H:\jeecg-cloud\jeecg-cloud-master\jeecg-cloud-master\jeecg-cloud-system\jeecg-cloud-system-biz\pom.xml) points at org.jeecgframework.cloud:jeecg-cloud-system instead of org.jeecgframework.cloud:jeecg-cloud, please verify your project structure @ line 7, column 13

**Comment by wyx666518** [comment]
jeecg-cloud-system\jeecg-cloud-system-biz\pom.xml的pom需要改成
<parent>
		<groupId>org.jeecgframework.cloud</groupId>
		<artifactId>jeecg-cloud</artifactId>
		<version>2.2.0</version>
		<relativePath/>
	</parent>，
加入<relativePath/>标签，但是依然提示Process terminated。。。

**Comment by zhangdaiscott** [comment]
更新代码了 ，已经修改了
