### ISSUE TITLE
Online表单开发中设置了字段只读，功能测试时表单实现了只读，生成代码后没有只读效果

### ISSUE THREAD

**Issue by Qiang-Ming** [zhangdaiscott/jeecg-cloud#21]
Online表单开发中设置了字段只读，功能测试时表单实现了只读，生成代码后没有只读效果，必须手动添加disabled。
图片上传空间手工添加disabled后，依然会出现上传的按钮，功能测试时不会出现。

**Comment by zhangdaiscott** [comment]
目前生成不支持，需要手工调整
