### ISSUE TITLE
能否直接用boot版的代码替换cloud的System模块来实现版本升级

### ISSUE THREAD

**Issue by Qiang-Ming** [zhangdaiscott/jeecg-cloud#23]
目前发现cloud版很多代码老旧未更新，导致一些boot版已经解决的bug还存在于cloud版本中，能否直接将boot版后台代码部分覆盖cloud版，实现版本的更新，以便修复一些bug！

**Comment by zhangdaiscott** [comment]
马上会出微服务和单体自由切换的版本，9月份差不多
