### ISSUE TITLE
启动项目报错, Error creating bean with name 'shiroConfig'

### ISSUE THREAD

**Issue by Dreamdzp** [zhangdaiscott/jeecg-cloud#5]
启动网关项目后, 启动JeecgSystemApplication和JeecgDemoApplication两个项目时均报错,
使用的版本为: 2020年6月1日1点提交的版本
报错如下:
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shiroConfig': Injection of autowired dependencies failed; 
nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'jeecg.shiro.excludeUrls' in value "${jeecg.shiro.excludeUrls}"

**Comment by Dreamdzp** [comment]
不好意思, 文档少看了两步

**Comment by tinygg** [comment]
> 不好意思, 文档少看了两步

我也出现这个问题，怎么解决的

**Comment by Dreamdzp** [comment]
配置nacos,


并创建两个属性文件&nbsp;配置列表，注意类型选择YAML

 jeecg-cloud/doc/NACOSCONFIG/application-jeecg-cloud.yml  jeecg-cloud/doc/NACOSCONFIG/jeecg-cloud-gateway.yml






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhang Wei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月3日(星期五) 上午9:31
收件人:&nbsp;"zhangdaiscott/jeecg-cloud"<jeecg-cloud@noreply.github.com&gt;;
抄送:&nbsp;"may the force be with me"<2423744374@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangdaiscott/jeecg-cloud] 启动项目报错, Error creating bean with name 'shiroConfig' (#5)





  
不好意思, 文档少看了两步
  
我也出现这个问题，怎么解决的

**Comment by tinygg** [comment]
> 配置nacos, 并创建两个属性文件&nbsp;配置列表，注意类型选择YAML jeecg-cloud/doc/NACOSCONFIG/application-jeecg-cloud.yml jeecg-cloud/doc/NACOSCONFIG/jeecg-cloud-gateway.yml
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Zhang Wei"<notifications@github.com&gt;; 发送时间:&nbsp;2020年7月3日(星期五) 上午9:31 收件人:&nbsp;"zhangdaiscott/jeecg-cloud"<jeecg-cloud@noreply.github.com&gt;; 抄送:&nbsp;"may the force be with me"<2423744374@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [zhangdaiscott/jeecg-cloud] 启动项目报错, Error creating bean with name 'shiroConfig' (#5) 不好意思, 文档少看了两步 我也出现这个问题，怎么解决的 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

nacos配置还这样（服务器上配置的，本机调试），怎么看是否从nacos拉到了配置呢

**Comment by Dreamdzp** [comment]
1.确保本机可以连接服务器
2.确保nacos中的安装成功
3.检查nacos中的配置文件格式及内容正确
4.修改jeecg-cloud-master\jeecg-cloud-system\jeecg-cloud-system-biz\src\main\resources\bootstrap.yml文件中的nacos-discovery的server-addr为服务器地址,
nacos:
      discovery:
        server-addr: 172.16.**.**:8848

**Comment by tinygg** [comment]
> 1.确保本机可以连接服务器
> 2.确保nacos中的安装成功
> 3.检查nacos中的配置文件格式及内容正确
> 4.修改jeecg-cloud-master\jeecg-cloud-system\jeecg-cloud-system-biz\src\main\resources\bootstrap.yml文件中的nacos-discovery的server-addr为服务器地址,
> nacos:
> discovery:
> server-addr: 172.16.**.**:8848

谢谢，这个master没问题，之前那个问题是gitee上的v1.0.0-beta产生的

**Comment by oryzivora** [comment]
> > 1.确保本机可以连接服务器
> > 2.确保nacos中的安装成功
> > 3.检查nacos中的配置文件格式及内容正确
> > 4.修改jeecg-cloud-master\jeecg-cloud-system\jeecg-cloud-system-biz\src\main\resources\bootstrap.yml文件中的nacos-discovery的server-addr为服务器地址,
> > nacos:
> > discovery:
> > server-addr: 172.16.**.**:8848
> 
> 谢谢，这个master没问题，之前那个问题是gitee上的v1.0.0-beta产生的

老哥 我现在用最新版2.4按照文档和视频操作
nacos配置完成
demo注释掉
spring-boot-maven-plugin修改为true
之后启动JeecgSystemCloudApplication 仍然报这个错 请问您是如何解决的
