### ISSUE TITLE
bootstrap无法读取pom文件

### ISSUE THREAD

**Issue by Nicky213Zhang** [zhangdaiscott/jeecg-cloud#6]
spring:
  application:
    name: @artifactId@
报错：
org.yaml.snakeyaml.scanner.ScannerException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
手动修改就可以了，网上找的也没能解决问题

**Comment by zhangdaiscott** [comment]
你这是那个工程

**Comment by zhangdaiscott** [comment]
```

 <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
```

**Comment by Nicky213Zhang** [comment]
加了<resources>也还是不行，本身gateway模块是有的，但是也启动不了，索性都写死了，这个问题倒是没什么，就是我取不到pom参数值罢了。然后docker-compose脚本还建议完善完善，包括：文件挂载、密码配置，，，当然这些我们也是需要自行处理一部分的。我愣是弄了一天才算完美启动，尴尬。。。
