### ISSUE TITLE
demo模块feign远程调用失效

### ISSUE THREAD

**Issue by Nicky213Zhang** [zhangdaiscott/jeecg-cloud#8]
NacosDemoController：调用userServiceClient.getUserInfo(request, token)方法总是失败，其余方法都可以执行。跟踪发现走不到system，直接被熔断器执行到fallback去了，关闭熔断，报以下错误：
"操作失败，Could not write JSON: Infinite recursion (StackOverflowError); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: org.xnio.nio.WorkerThread[\"worker\"]->org.xnio.nio.NioXnioWorker[\"ioThread\"]->org.xnio.nio.WorkerThread[\"worker\"]->org.xnio.nio.NioXnioWorker[\"ioThread\"]->org.xnio.nio.WorkerThread[\"worker\"]

**Comment by zhangdaiscott** [comment]
这个方法是刚开始测试用的，后来作废了，这个接口要删掉的
